### ISSUE TITLE
"r" property of Margins doesn't appear in Plotly Figure Reference Documentation

### ISSUE THREAD

**Issue by nicolebryant** [plotly/graphing-library-docs#31]
Reviewing a PR on a code base that is working to implement Plotly, it was discovered that the "r" property of layout>margins appears in the search function of Plotly's documentation/figure reference but not in the documentation or figure references themselves. Is this an update to Plotly code?

To recreate this issue:
- Browser: Google Chrome
- View a Plotly documentation site (this issue appears to happen on both the Plotly's Python and JavaScript graphing documentation)
- Using search feature, enter "margin>r" or "layout>margin>r"
        - Notice that the matching property appears in the "Figure Reference Results"
        - Clicking on the link brings you to the generic Figure Reference Page
- Clicking through the right hand contents list:
        - Scrolled to section titled "Layout"
        - Selected "Margins" link to view Margins Figure Reference 
        - No property labelled as "r" appears here

**Comment by nicolaskruchten** [comment]
Thanks for the bug report! This is quite strange indeed, and is not intentional. Let me take a look :)

**Comment by nicolaskruchten** [comment]
Wow, this is a pretty gross bug... Turns out our templating engine doesn't respect parentheses in conditionals!

![image](https://user-images.githubusercontent.com/203523/77166533-cddc0100-6a8a-11ea-8447-8c77ffaa0033.png)

The fix is deploying right now and should be live in 10 minutes or so. Thanks again for pointing this out :)
