### ISSUE TITLE
Revamp tile look on index pages

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/graphing-library-docs#69]
NEW:

![image](https://user-images.githubusercontent.com/203523/80403158-24f4a300-888d-11ea-90dc-a66c2d7ef93b.png)

OLD:

![image](https://user-images.githubusercontent.com/203523/80403185-350c8280-888d-11ea-8c8b-9c5643099224.png)

**Comment by nicolaskruchten** [comment]
We should actually be able to do better than this on an iPhone screen:

![image](https://user-images.githubusercontent.com/203523/80403468-a0565480-888d-11ea-8cb0-83bce8c12021.png)

**Comment by nicolaskruchten** [comment]
Also, the sub-index pages should not have the word "more" in their titles:

![image](https://user-images.githubusercontent.com/203523/80403595-d5fb3d80-888d-11ea-8174-fedc9c8207d9.png)

**Comment by nicolaskruchten** [comment]
Also, I've always found it pretty redundant to have this little sub-heading:

![image](https://user-images.githubusercontent.com/203523/80403693-0347eb80-888e-11ea-8803-3ec70bf5153c.png)

**Comment by jdamiba** [comment]
@nicolaskruchten Please take a look at the latest Percy diffs. 

items completed:

- [x] apply drop shadow to thumbnail
- [x] remove grey background from example title
- [x] add "more" hyperlink for each section
- [x] fix mobile alignment
- [x] remove "more" from subindex page titles
- [x] remove redundant section heading on subindex pages

items outstanding:
- [ ] PRs in plolty.py and plotly.r-docs so that "more" posts do not show up on example index
- [ ] update CI script to accept and validate new front-matter structure

**Comment by nicolaskruchten** [comment]
Good start! there are some alignment issues which we can work on :)

Are you looking to deploy this soon or is there more work you want to do first? I haven't built it locally to play with how it responds to changing screen sizes.

**Comment by jdamiba** [comment]
No, I am not looking to deploy this PR currently- I would like to complete the items marked as `outstanding` first. 

My goal is to deploy on Wednesday if that is OK.
